# Generated by Django 4.1.2 on 2022-10-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_options_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, verbose_name="Review"),
        ),
    ]
