# Generated by Django 4.1.2 on 2022-10-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_review_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Enter a brief description of the book.",
                max_length=1000,
            ),
        ),
    ]
