# Generated by Django 4.1.2 on 2022-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_rename_author_review_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pubdate",
            field=models.DateField(
                blank=True, help_text="Date of Publication", null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
