# Generated by Django 4.0.5 on 2022-06-23 17:12

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_groups_alter_customuser_is_active",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name of User"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
    ]
